---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-operator
  namespace: prometheus-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-operator
  namespace: prometheus-operator
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator
  namespace: prometheus-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-operator
subjects:
  - kind: ServiceAccount
    name: prometheus-operator
    namespace: default
