# color-svc makes
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: color-svc
  namespace: playground
---
apiVersion: v1
kind: Service
metadata:
  name: color-svc
  namespace: playground
  labels:
    app.kubernetes.io/name: color-svc
spec:
  ports:
    - name: http
      port: 8800
      targetPort: 8800
  selector:
    app.kubernetes.io/name: color-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-svc
  namespace: playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: color-svc
      app.kubernetes.io/version: v1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: color-svc
        app.kubernetes.io/version: v1
    spec:
      serviceAccountName: color-svc
      containers:
        - image: docker.io/rytswd/color-svc:latest
          name: color-svc
          imagePullPolicy: Always
          command:
            - color-svc
          ports:
            - containerPort: 8800
          env:
            - name: ENABLE_DELAY
              value: "true"
            - name: DISABLE_RED
              value: "false" # The same as default
            - name: DISABLE_GREEN
              value: "false" # The same as default
            - name: DISABLE_BLUE
              value: "false" # The same as default
            - name: DISABLE_YELLOW
              value: "false" # The same as default
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 30m
              memory: 30Mi
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: color-svc
spec:
  hosts:
    - color-svc.playground.svc.cluster.local
  gateways:
    - mesh
  http:
    - match:
        - uri:
            prefix: /istio
      rewrite:
        uri: /
      route:
        - destination:
            host: color-svc-only-red.playground.svc.cluster.local
            port:
              number: 8800
          weight: 50
        - destination:
            host: color-svc-only-blue.playground.svc.cluster.local
            port:
              number: 8800
          weight: 50
      fault:
        abort:
          percentage:
            value: 50
          httpStatus: 400
    - route:
        - destination:
            host: color-svc.playground.svc.cluster.local
            port:
              number: 8800
