---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: prometheus-no-mtls
  namespace: thanos
spec:
  mtls:
    mode: DISABLE
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos

---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
spec:
  mtls:
    mode: STRICT
