---
# Turn on mTLS by default for all workloads
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default-mtls-required
spec:
  mtls:
    mode: STRICT

---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: prometheus-no-mtls
  namespace: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-istio
  mtls:
    mode: UNSET # Inherit what's used, or use PERMISSIVE if none
  # portLevelMtls:
  #   10901:
  #     mode: DISABLE
