---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: prometheus-no-mtls
  namespace: prometheus
spec:
  # selector:
  #   matchLabels:
  #     app.kubernetes.io/name: prometheus-istio
  mtls:
    mode: UNSET
  # portLevelMtls:
  #   10901:
  #     mode: DISABLE

---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
spec:
  mtls:
    mode: STRICT
