---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: prometheus-no-mtls
  namespace: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
      app.kubernetes.io/name: prometheus-istio
      controller-revision-hash: prometheus-istio-59fc6b874c
      istio.io/rev: default
      operator.prometheus.io/name: istio
      operator.prometheus.io/shard: "0"
      prometheus: istio
      security.istio.io/tlsMode: istio
      service.istio.io/canonical-name: prometheus-istio
      service.istio.io/canonical-revision: latest
      statefulset.kubernetes.io/pod-name: prometheus-istio-0
  mtls:
    mode: DISABLE

---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
spec:
  mtls:
    mode: STRICT
