---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: prometheus-no-mtls
  namespace: prometheus
spec:
  mtls:
    mode: DISABLE
  selector:
    matchLabels:
      app: prometheus

---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
spec:
  mtls:
    mode: STRICT
