---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: prometheus
  namespace: prometheus
spec:
  mtls:
    mode: DISABLE
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-istio

---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
spec:
  mtls:
    mode: STRICT
