{{- range .Values.apps }}
{{- if and .enabled .namespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .namespace }}
  {{- if .istioSidecar }}
  labels:
    istio-injection: enabled
    {{- if .istioRevision }}
    istio.io/rev: {{ .istioRevision }}
    {{- end }}
  {{- end }}
...
{{- end }}
{{- end }}