{{- range .Values.apps }}
{{- if and .enabled .namespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .namespace }}
  {{- if .istioSidecar }}
  labels:
    istio-injection: enabled
  {{- end }}
...
{{- end }}
{{- end }}