---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app.kubernetes.io/name: httpbin
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 80
  selector:
    app.kubernetes.io/name: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-old
  namespace: playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: httpbin
      version: v1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: httpbin
        version: v1
    spec:
      serviceAccountName: httpbin
      containers:
        - image: docker.io/kennethreitz/httpbin
          imagePullPolicy: IfNotPresent
          name: httpbin
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-new
  namespace: playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: httpbin
      version: v2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: httpbin
        version: v2
    spec:
      serviceAccountName: httpbin
      containers:
        - image: docker.io/kennethreitz/httpbin
          imagePullPolicy: IfNotPresent
          name: httpbin
          ports:
            - containerPort: 80
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: httpbin
spec:
  host: httpbin.playground.svc.cluster.local
  subsets:
    - name: old
      labels:
        app.kubernetes.io/name: toolkit-alpine
        version: v1
    - name: new
      labels:
        app.kubernetes.io/name: toolkit-alpine
        version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-chaos-routing
spec:
  hosts:
    - httpbin.playground.svc.cluster.local
  gateways:
    - mesh
  http:
    - match:
        - uri:
            prefix: /chaos
      rewrite:
        uri: /status/418
      route:
        - destination:
            host: httpbin.default.svc.cluster.local
            subset: new
      fault:
        abort:
          percentage:
            value: 50
          httpStatus: 400
