---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rpc-app
  labels:
    env: production
spec:
  selector:
    matchLabels:
      app: rpc-app
  endpoints:
    - port: web
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: color-svc
  labels:
    env: production
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: color-svc
  endpoints:
    - port: web
