apiVersion: v1
kind: ServiceAccount
metadata:
  name: toolkit-alpine
  namespace: playground
---
apiVersion: v1
kind: Service
metadata:
  name: toolkit-alpine
  namespace: playground
  labels:
    app: toolkit-alpine
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 80
  selector:
    app: toolkit-alpine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolkit-alpine
  namespace: playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toolkit-alpine
      version: v1
  template:
    metadata:
      labels:
        app: toolkit-alpine
        version: v1
    spec:
      serviceAccountName: toolkit-alpine
      containers:
        - image: docker.io/rytswd/toolkit-alpine:0.1.1
          name: toolkit-alpine
          command: ["/bin/sleep", "3650d"]
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 30m
              memory: 30Mi
