apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: prometheus
spec:
  egress:
    - hosts:
        - istio-system/istiod.istio-system.svc.cluster.local
  workloadSelector:
    labels:
      app.kubernetes.io/name: prometheus-istio
