apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Because Istio sidecar needs to be placed with Prometheus, this needs to be
# some namespace with Istio sidecar enablement.
namespace: prometheus

secretGenerator:
  - name: istio-scrape-configs
    files:
      - ./istio-scrape-configs.yaml

generatorOptions:
  disableNameSuffixHash: true

resources:
  - prometheus-istio.yaml
  - prometheus-istio-rbac.yaml
  - prometheus-istio-monitor.yaml
  # - istio-scrape-configs-secret.yaml
