# Ensure Thanos Store Gateway and MinIO are accessible from Prometheus Pod.
# Unlike Prometheus, Thanos cannot use TLS setup, and thus this workaround is needed.
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: thanos-gateway
spec:
  host: thanos-gateway.thanos.svc.cluster.local
  exportTo:
    - "."
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: thanos-minio
spec:
  host: thanos-minio.thanos.svc.cluster.local
  exportTo:
    - "."
  trafficPolicy:
    tls:
      mode: DISABLE
