apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

secretGenerator:
  - name: istio-scrape-configs
    files:
      - ./istio-scrape-configs.yaml
    namespace: upsidr-system

generatorOptions:
  disableNameSuffixHash: true

resources:
  - prometheus-istio.yaml
  - prometheus-istio-rbac.yaml
  - prometheus-istio-monitor.yaml
  - istio-scrape-configs-secret.yaml
