- job_name: "federate"
  scrape_interval: 10s
  honor_labels: true
  metrics_path: "/federate"
  params:
    "match[]":
      - '{__name__=~"federate:(.*)"}'
  static_configs:
    - targets:
        - "prometheus-istio:9090"
  metric_relabel_configs:
    - source_labels: [__name__]
      regex: "federate:(.*)"
      target_label: __name__
      action: replace
