# Ref: https://github.com/bitnami/charts/blob/master/bitnami/thanos/values.yaml
thanos:
  image:
    registry: quay.io/thanos
    repository: thanos
    tag: v0.18.0

  query:
    replicaCount: 2
    dnsDiscovery:
      sidecarsService: prometheus-istio
      sidecarsNamespace: prometheus
