apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-demo
  namespace: istio-system
spec:
  profile: demo

  components:
    pilot:
      k8s:
        # Reduce resource requirements for local testing. This is NOT
        # recommended for the real use cases.
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
