apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Because Istio sidecar needs to be placed with Prometheus, this needs to be
# some namespace with Istio sidecar enablement.
namespace: prometheus

secretGenerator:
  - name: thanos-storage-config
    files:
      - ./thanos-storage.yaml

generatorOptions:
  disableNameSuffixHash: true

resources:
  - federation.yaml
  - federation-rbac.yaml
  - istio-federation-monitor.yaml
