---
# Ref: https://www.jaegertracing.io/docs/1.21/operator/#understanding-custom-resource-definitions
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  startegy: allInOne
  allInOne:
    query:
      base-path: /jaeger
  query:
    options:
      base-path: /jaeger
      query:
        base-path: /jaeger
  ui:
    options:
      base-path: /jaeger
      query:
        base-path: /jaeger
  ingress:
    enabled: false
