---
# Ref: https://www.jaegertracing.io/docs/1.21/operator/#understanding-custom-resource-definitions
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  startegy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:1.16
    log-level: debug
    query:
      base-path: /jaeger
  ingress:
    enabled: false
