---
# Ref: https://www.jaegertracing.io/docs/1.21/operator/#understanding-custom-resource-definitions
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: prod
spec:
  strategy: production
  collector:
    maxReplicas: 3
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
