vitess:
  topology:
    cells:
      - name: "zone1"
        etcd:
          replicas: 3
        vtctld:
          replicas: 1
        vtgate:
          replicas: 3
        mysqlProtocol:
          enabled: false
        keyspaces:
          - name: "unsharded_dbname"
            shards:
              - name: "0"
                tablets:
                  - type: "replica"
                    vttablet:
                      replicas: 2