---
# Ref: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: istio
spec:
  replicas: 1
  podMetadata:
    labels:
      app.kubernetes.io/name: prometheus-istio
    # Taken from https://istio.io/latest/docs/ops/integrations/prometheus/
    annotations:
      sidecar.istio.io/inject: "true"
      traffic.sidecar.istio.io/includeInboundPorts: "" # do not intercept any inbound ports
      traffic.sidecar.istio.io/includeOutboundIPRanges: "" # do not intercept any outbound traffic
      proxy.istio.io/config:
        | # configure an env variable `OUTPUT_CERTS` to write certificates to the given folder
        proxyMetadata:
          OUTPUT_CERTS: /etc/istio-output-certs
      sidecar.istio.io/userVolume: '[{"name": "istio-certs", "emptyDir": {"medium":"Memory"}}]' # mount the shared volume
      sidecar.istio.io/userVolumeMount: '[{"name": "istio-certs", "mountPath": "/etc/istio-output-certs"}]'

  # TODO: Configure DNS and ingress to be able to connect
  externalUrl: http://localhost
  routePrefix: "/prometheus"

  serviceAccountName: prometheus-istio

  retention: "10d"
  # portName: web

  serviceMonitorNamespaceSelector: {} # auto discovers all service monitors across all namespaces
  serviceMonitorSelector: {} # auto discovers all service monitors in namespaces configured one line above
  ruleNamespaceSelector: {} # auto discovers all prometheus rules across all namespaces
  ruleSelector: {} # auto discovers all prometheus rules in namespaces configured one line above

  additionalScrapeConfigs:
    key: istio-scrape-configs.yaml
    name: istio-scrape-configs

  # Taken from https://istio.io/latest/docs/ops/integrations/prometheus/
  volumeMounts:
    - mountPath: /etc/prom-certs/
      name: istio-certs

  volumes:
    - name: istio-certs
      emptyDir: {}

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus-istio
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-istio
  labels:
    app.kubernetes.io/name: prometheus-istio
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9090
      targetPort: 9090
  selector:
    app.kubernetes.io/name: prometheus-istio
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: prometheus-istio
  labels:
    app.kubernetes.io/name: prometheus-istio
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-istio
