apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: simple
  labels:
    app.kubernetes.io/name: simple-prometheus
spec:
  replicas: 1

  # TODO: Configure DNS and ingress to be able to connect
  externalUrl: http://localhost
  routePrefix: "/"

  serviceAccountName: prometheus

  retention: "10d"
  # portName: web

  serviceMonitorNamespaceSelector: {} # auto discovers all service monitors across all namespaces
  serviceMonitorSelector: {} # auto discovers all service monitors in namespaces configured one line above
  ruleNamespaceSelector: {} # auto discovers all prometheus rules across all namespaces
  ruleSelector: {} # auto discovers all prometheus rules in namespaces configured one line above

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: simple
  labels:
    app.kubernetes.io/name: simple-prometheus
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9090
      targetPort: 9090
  selector:
    app.kubernetes.io/name: simple-prometheus
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: simple-prometheus
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: simple-prometheus
