# Ref: https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
grafana:
  namespaceOverride: istio-system # Deploys against this namespace

  persistence:
    enabled: true

  grafana.ini:
    auth.anonymous:
      enabled: true
      org_name: test-org
      org_role: Viewer
